name: HetimaPatrinia
version: 0.0.05
author: kyorohiro
description: A sample Chrome packaged application
dependencies:
  ace: any
  chrome: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore.git
  hetimafile:
    git: https://github.com/kyorohiro/dart_hetimafile.git
  hetimagit:
    git: https://github.com/kyorohiro/dart_hetimagit.git
  textencoding_js:
    path: jstextencoding
dev_dependencies:
  ace_js:
    path: jsace
transformers:
- chrome
- $dart2js:
    csp: true
