name: HetimaPatrinia
version: 0.0.05
author: kyorohiro
description: A sample Chrome packaged application
dependencies:
  ace: any
  chrome: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore
  hetimafile:
    path: /Users/kiyohiro/dart/git/dart_hetimafile
  hetimagit:
    path: /Users/kiyohiro/dart/git/dart_hetimagit
  textencoding_js:
    path: jstextencoding
dev_dependencies:
  ace_js:
    path: jsace
transformers:
- chrome
- $dart2js:
    csp: true
