name: HetimaPatrinia
version: 0.0.01
author: kyorohiro
description: A sample Chrome packaged application
dependencies:
  ace: any
  chrome: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore.git
  hetimagit:
    path: /Users/kiyohiro/dart/git/dart_hetimagit
dev_dependencies:
  ace_js:
    path: js
transformers:
- chrome
- $dart2js:
    csp: true
